spring.application.name=activEducation

# PostgreSQL (dev local)
spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:activ_education}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:abalakata}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / HIBERNATE
spring.jpa.hibernate.ddl-auto=${JPA_DDL_AUTO:update}
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
spring.jpa.properties.hibernate.temp.use_jdbc_metadata_defaults=false
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.default_batch_fetch_size=100

# Bean Validation (JPA/Hibernate)
spring.jpa.properties.jakarta.persistence.validation.mode=auto
spring.jpa.properties.hibernate.validator.fail_fast=true

# Server
server.port=${SERVER_PORT:8080}

# Logs
logging.level.root=INFO
logging.level.tg.edtch.activEducation=DEBUG

# Swagger / OpenAPI (springdoc)
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha
springdoc.swagger-ui.doc-expansion=none
springdoc.swagger-ui.filter=true
springdoc.swagger-ui.try-it-out-enabled=true
springdoc.show-actuator=false
springdoc.packages-to-scan=tg.edtch.activEducation
springdoc.paths-to-match=/**
springdoc.default-produces-media-type=application/json
springdoc.default-consumes-media-type=application/json

# MinIO
minio.url=${MINIO_URL:http://localhost:9000}
minio.access-key=${MINIO_ACCESS_KEY:minio}
minio.secret-key=${MINIO_SECRET_KEY:abalakata}
minio.bucket.images=${MINIO_BUCKET_IMAGES:activeducation-images}
minio.bucket.videos=${MINIO_BUCKET_VIDEOS:activeducation-videos}
minio.bucket.documents=${MINIO_BUCKET_DOCUMENTS:activeducation-documents}

# Configuration Multipart (Upload de fichiers jusqu'à 500MB)
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=500MB
spring.servlet.multipart.max-request-size=500MB
