spring.datasource.url=jdbc:h2:mem:activ_education;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=PostgreSQL
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true

spring.jpa.hibernate.ddl-auto=create

# spring.jpa.properties.hibernate.globally_quoted_identifiers=true

spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.password=
spring.data.redis.database=0

minio.url=http://localhost:9000
minio.access-key=minioadmin
minio.secret-key=minioadmin

logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=DEBUG

security.jwt.secret=O4a/7n23FFH7n7lMn1UvCPYCLlB+iwm/8+wDR0Fvr9ozp3zGXmyYIZyNa1mgVZheHXYkmlVh6+V7Jxrnw2/iXQ==
gemini.api.key=test-key

rate.limit.login.max=99999
rate.limit.refresh.max=99999
rate.limit.api.max=99999
