spring.datasource.url=jdbc:postgresql://localhost:5432/activ_education
spring.datasource.username=postgres
spring.datasource.password=abalakata
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.hibernate.ddl-auto=update

# spring.jpa.properties.hibernate.globally_quoted_identifiers=true

spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.password=
spring.data.redis.database=0

minio.url=http://localhost:9000
minio.access-key=minioadmin
minio.secret-key=minioadmin

logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=DEBUG

security.jwt.secret=O4a/7n23FFH7n7lMn1UvCPYCLlB+iwm/8+wDR0Fvr9ozp3zGXmyYIZyNa1mgVZheHXYkmlVh6+V7Jxrnw2/iXQ==
gemini.api.key=test-key

rate.limit.login.max=99999
rate.limit.refresh.max=99999
rate.limit.api.max=99999
